# Enables standalone use when this package is synced to Scaffald/ui.
# Catalog entries are required because package.json uses "catalog:" and
# the standalone repo has no monorepo catalog. In the monorepo, the root
# pnpm-workspace.yaml takes precedence.
packages:
  - '.'
  - 'docs-site'

catalog:
  '@biomejs/biome': ~2.3.14
  '@react-native-async-storage/async-storage': 2.2.0
  react-dropzone: ~14.3.8
  react-dom: ^19.2.0
  typescript: ~5.9.3
