import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'guide/installation',
        'guide/quick-start',
        'guide/theming',
      ],
    },
    {
      type: 'category',
      label: 'Design Tokens',
      collapsed: true,
      items: [
        'tokens/overview',
      ],
    },
    'contributing',
  ],

  // Components sidebar - all available components
  componentsSidebar: [
    'components/overview',
    {
      type: 'category',
      label: 'All Components',
      collapsed: false,
      items: [
        'components/accordion',
        'components/alert',
        'components/app-store-button',
        'components/appearance-theme-card',
        'components/avatar',
        'components/breadcrumb',
        'components/button-group',
        'components/button',
        'components/card',
        'components/chart',
        'components/checkbox',
        'components/checklist',
        'components/chip',
        'components/command-menu-footer',
        'components/command-menu-item',
        'components/command-menu',
        'components/command-shortcut',
        'components/crypto-asset-card',
        'components/crypto-wallet-layout',
        'components/date-picker-base',
        'components/date-picker-day',
        'components/date-picker-header',
        'components/date-picker',
        'components/dropdown',
        'components/field-error',
        'components/file-upload',
        'components/form',
        'components/grid',
        'components/helper-text',
        'components/icon-selector',
        'components/icon',
        'components/input',
        'components/legend-indicator',
        'components/list-item',
        'components/list',
        'components/loading-overlay',
        'components/modal',
        'components/nav-icon-button',
        'components/notification-list-item',
        'components/notification-tag',
        'components/onboarding',
        'components/pagination',
        'components/password-strength',
        'components/phone-number-input',
        'components/popover',
        'components/progress-bar',
        'components/radio',
        'components/responsive-select',
        'components/responsive',
        'components/rich-text-editor',
        'components/saa-snavigation',
        'components/saa-ssection-header',
        'components/save-status-indicator',
        'components/scroll-area',
        'components/search-select',
        'components/selection-card',
        'components/settings-form-field',
        'components/settings-integrations-grid',
        'components/settings-notification-table',
        'components/settings-page-layout',
        'components/settings-section-header',
        'components/settings-team-table',
        'components/settings-toggle-card',
        'components/sheet',
        'components/sidebar',
        'components/skeleton',
        'components/slider',
        'components/social-button',
        'components/spinner',
        'components/status-indicator',
        'components/stepper',
        'components/table',
        'components/tabs',
        'components/toast',
        'components/toggle',
        'components/tooltip',
        'components/trade-controls',
      ],
    },
  ],
};

export default sidebars;
