/**
 * Default icon names (Lucide) for IconSelector.
 * Must match exports from lucide-react-native.
 */

export const DEFAULT_ICON_NAMES = [
  'UserSearch',
  'Share2',
  'Sprout',
  'Home',
  'User',
  'Users',
  'Building2',
  'Briefcase',
  'Map',
  'Star',
  'Heart',
  'MessageCircle',
  'Bell',
  'Settings',
  'Search',
  'Filter',
  'Calendar',
  'Clock',
  'Mail',
  'Phone',
  'MapPin',
  'Globe',
  'FileText',
  'Image',
  'Video',
  'Music',
  'Download',
  'Upload',
  'Eye',
  'EyeOff',
  'ThumbsUp',
  'ThumbsDown',
  'Share',
  'Send',
  'Edit',
  'Trash2',
  'Plus',
  'Minus',
  'Check',
  'X',
  'ChevronRight',
  'ChevronLeft',
  'ChevronUp',
  'ChevronDown',
  'ArrowRight',
  'ArrowLeft',
  'ArrowUp',
  'ArrowDown',
  'MoreHorizontal',
  'MoreVertical',
] as const

export type DefaultIconName = (typeof DEFAULT_ICON_NAMES)[number]
